### ISSUE TITLE
Screen Share Intergration

### ISSUE THREAD

**Issue by drexhacker** [GetStream/stream-video-flutter#689]
Hello am running into the following issue
```
FATAL EXCEPTION: main
E/AndroidRuntime( 8803): Process: com.hsecampus.app, PID: 8803
E/AndroidRuntime( 8803): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 8803):        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
E/AndroidRuntime( 8803):        at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime( 8803):        at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime( 8803):        at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime( 8803):        at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:235)
E/AndroidRuntime( 8803):        at android.media.projection.MediaProjection.<init>(MediaProjection.java:59)
E/AndroidRuntime( 8803):        at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:119)
E/AndroidRuntime( 8803):        at com.cloudwebrtc.webrtc.OrientationAwareScreenCapturer.startCapture(OrientationAwareScreenCapturer.java:117)
E/AndroidRuntime( 8803):        at com.cloudwebrtc.webrtc.GetUserMediaImpl.getDisplayMedia(GetUserMediaImpl.java:559)
E/AndroidRuntime( 8803):        at com.cloudwebrtc.webrtc.GetUserMediaImpl.access$300(GetUserMediaImpl.java:88)
E/AndroidRuntime( 8803):        at com.cloudwebrtc.webrtc.GetUserMediaImpl$4.onReceiveResult(GetUserMediaImpl.java:507)
E/AndroidRuntime( 8803):        at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime( 8803):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 8803):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8803):        at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8803):        at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8803):        at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 8803):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8803):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8803):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 8803): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 8803):        at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:482)
E/AndroidRuntime( 8803):        at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
E/AndroidRuntime( 8803):        at android.os.Binder.execTransactInternal(Binder.java:1179)
E/AndroidRuntime( 8803):        at android.os.Binder.execTransact(Binder.java:1143)
E/AndroidRuntime( 8803): 
I/org.webrtc.Logging( 8803): CameraStatistics: Camera fps: 9.
D/FlutterWebRTCPlugin( 8803): onConnectionChangeCONNECTED
I/Process ( 8803): Sending signal. PID: 8803 SIG: 9
```

When I enable screenshare on my call type I get this dialog then the app crushes
![image](https://github.com/GetStream/stream-video-flutter/assets/63024937/db975833-8fac-416b-80ff-ffb098aa8e13)

**Comment by drexhacker** [comment]
I have found a temporary workaround which is to  change the `android/app/build.gradle` `targetSdkVersion` to `33` instead of `34`.

Hope it really helps someone.

**Comment by mlab817** [comment]
that didn't fix it for me. i still get this error:

D/AndroidRuntime(16311): Shutting down VM
E/AndroidRuntime(16311): FATAL EXCEPTION: main
E/AndroidRuntime(16311): Process: io.getstream.video.flutter.dogfooding.debug, PID: 16311
E/AndroidRuntime(16311): java.lang.RuntimeException: Unable to create service io.getstream.video.flutter.stream_video_flutter.service.StreamScreenShareService: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{95d7b5d 16311:io.getstream.video.flutter.dogfooding.debug/u0a198} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] 
E/AndroidRuntime(16311): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4973)
E/AndroidRuntime(16311): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(16311): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2427)
E/AndroidRuntime(16311): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(16311): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(16311): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(16311): 	at android.app.ActivityThread.main(ActivityThread.java:8674)
E/AndroidRuntime(16311): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16311): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime(16311): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
E/AndroidRuntime(16311): Caused by: java.lang.SecurityException: Starting FGS with type mediaProjection callerApp=ProcessRecord{95d7b5d 16311:io.getstream.video.flutter.dogfooding.debug/u0a198} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_MEDIA_PROJECTION] any of the permissions allOf=false [android.permission.CAPTURE_VIDEO_OUTPUT, android:project_media] 
E/AndroidRuntime(16311): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3242)
E/AndroidRuntime(16311): 	at android.os.Parcel.createException(Parcel.java:3226)
E/AndroidRuntime(16311): 	at android.os.Parcel.readException(Parcel.java:3209)
E/AndroidRuntime(16311): 	at android.os.Parcel.readException(Parcel.java:3151)
E/AndroidRuntime(16311): 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7164)
E/AndroidRuntime(16311): 	at android.app.Service.startForeground(Service.java:776)
E/AndroidRuntime(16311): 	at io.getstream.video.flutter.stream_video_flutter.service.StreamScreenShareService.startForeground(StreamScreenShareService.kt:89)
E/AndroidRuntime(16311): 	at io.getstream.video.flutter.stream_video_flutter.service.StreamScreenShareService.onCreate(StreamScreenShareService.kt:64)
E/AndroidRuntime(16311): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4960)
E/AndroidRuntime(16311): 	... 9 more
E/AndroidRuntime(16311): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(16311): 	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2882)
E/AndroidRuntime(16311): 	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2569)
E/AndroidRuntime(16311): 	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1835)
E/AndroidRuntime(16311): 	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14077)
E/AndroidRuntime(16311): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3578)
E/AndroidRuntime(16311):
