### ISSUE TITLE
Callkit notification show audio call icon even the call type has video enabled

### ISSUE THREAD

**Issue by TinhHuynh** [GetStream/stream-video-flutter#731]
I used the `default` call type with video enabled, but the push notification still shows the audio call icon. Is that an issue?

<img width="936" alt="ảnh" src="https://github.com/user-attachments/assets/24e31501-78f3-417a-80a9-a7fe04e200a3">

![ảnh](https://github.com/user-attachments/assets/3128453e-8628-4fde-baae-1b75dc34760d)

```
@override
  Future<Call> makeCall(String otherMemberId, {bool isVideo = true}) async {
    ....
    final call = _callClient!
        .makeCall(callType: video.StreamCallType(), id: const Uuid().v4());
   await call.getOrCreate(
        memberIds: ids,
        ringing: true,
       ).then((value) async {
       ...
    });
   ...
  }
```

Additionally, my app's video call function supports audio and video calls, but they can turn on/off the video during the call (after both users connect the call). Suppose I set up a custom type with Video Enabled = false for audio calls on the dashboard. Does the SDK support transmitting/receiving video streams if a user opens the camera during the audio call?

I appreciate any help you can provide.

**Comment by Brazol** [comment]
Hey @TinhHuynh, the approach for this has changed a little and is now more flexible, so it will also work well for your case. We [introduced](https://github.com/GetStream/stream-video-flutter/pull/735) the new parameter, `video` to the`call.getOtCreate()` method that indicates whether the call is a video or audio call. Based on this parameter the ringing notification will appear as video or audio call.

The pull request is merged and will be part of the next release. I hope this will solve your issue, otherwise feel free to reopen this ticket.
