### ISSUE TITLE
Web Support ?

### ISSUE THREAD

**Issue by rnp0728** [GetStream/stream-video-flutter#737]
Hi stream team,

I’m currently using the stream_video_flutter package to implement video calling features in my Flutter app. I’m interested in knowing if there are any plans or ongoing work to add support for web platforms.

Web support would be incredibly valuable for my project and would help ensure a consistent experience across all platforms. Could you provide any updates or timelines regarding this feature?

Thank you!

**Comment by drexhacker** [comment]
They should consider all other platforms just like stream_chat_flutter works everywhere. For My Case I want to implement a conferencing platform like zoom but Video Calls are limited to mobile

**Comment by rnp0728** [comment]
@drexhacker I didn't get it. Any resolutions for this?

**Comment by drexhacker** [comment]
> @drexhacker Any resolutions for solving this issue or do you know any other packages which provides support for all 3 platforms? 

All I can say this package is the best both in simplicity and usability regarding others am not very sure but for what I know they use the `flutter_webrtc` which supports all platforms, meaning you can extend this package on your own using flutter_webrtc and their api or core package. I'm also soon heading for this just that am still working on other things

**Comment by deven98** [comment]
Hey @rnp0728 👋 

Unlike most video calling packages for Flutter, we decided to build all possible functionality in Dart and use the flutter_webrtc package for the same (similar to the things mentioned by @drexhacker). At the moment, we *officially* support Android and iOS, but we also have *experimental support* for Web and MacOS. Our dogfooding app in the repo already works on these platforms. 

Still, we are some time away from official support which would also include relevant documentation, guides, as well as regular testing and workflows on all supported platforms.

While you can try the package out on other platforms today, we are some time away from guaranteeing full platform support. For the same, we are also in the process of expanding our Flutter team which would allow us to achieve this.  Hope this helps :)

**Comment by asaarnak** [comment]
Hei, @deven98! 
Any updates on official support for Web?

**Comment by asaarnak** [comment]
Hei! @renefloor, @Brazol, @d3xvn  
Are there any updates to Web support and other desktop platforms?

**Comment by renefloor** [comment]
Hi @asaarnak, currently no updates.

As said before, we focus on mobile with full support on Android and iOS. Internally we also run it on web and macos, so in general the sdk works on those platforms, but they might be missing features. Currently we don't test on windows and linux, so no promises there. 

We do like to know about interest in specific platforms though, so we can prioritize the support for them. Which platforms would you like to use and what kind of app do you want to make?

**Comment by asaarnak** [comment]
Web and MacOS. We plan to migrate our 1to1 video room and chat mobile app to desktop and web sometime in future. We need 1to1 call with ai transcribing and blur background. And also chat at the same time and send attachments.

**Comment by NullPointerException-25** [comment]
web and macos also

**Comment by asaarnak** [comment]
Hei! @renefloor, @Brazol, @d3xvn
Are there any updates to Web support and `flutter --wasm` support?

**Comment by renefloor** [comment]
@asaarnak most stuff works on Web.

For WASM we're waiting for a release for dart-webrtc with this commit:
https://github.com/flutter-webrtc/dart-webrtc/commit/e56dc4ac

We've also recently added a support table in the readme: https://pub.dev/packages/stream_video_flutter#supported-platforms

So basically web works, but our main focus is on android and iOS. The main reason is that there are so many different browser out there that we can't test and support them all. If you encounter some issues please let us know, because in general it should work. Features on web get lower priority though, for example background filters are still not implemented on web.

**Comment by mlab817** [comment]
We had to build a separate app for web just because web is not supported by `stream-video-flutter`. It's good that at least, it's now officially supported (was added in `1.4.2` based on git commit history). I think it would have been nice to announce it in the website and mention the limitations in the docs. For now, I guess we can just add a banner in a flutter web app informing the user of the limitations in web and download our mobile app. But now, at least our flutter app would compile in web and that's really nice.

**Comment by asaarnak** [comment]
@renefloor Thanks, hopefully WASM support arrives soon, we will release our app probably in about 2 months, until then we will use the stream-video-js javascript SDK with bridge mappings to flutter code.

**Comment by asaarnak** [comment]
@renefloor dart-webrtc is released now.

**Comment by renefloor** [comment]
@asaarnak thanks for the heads up, I did some testing and the video sdk works out of the box. The index.html in the examples was outdated though and the chat sdk has a wrong import, so made 2 PR's on our repo's to fix it. Please let us know if you find any other issues.
