### ISSUE TITLE
flutter_callkit_incoming issue when trying to use debug run.

### ISSUE THREAD

**Issue by YashSavsani** [GetStream/stream-video-flutter#784]
Execution failed for task ':flutter_callkit_incoming:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.

Please help solve this issue.

SDK version used

stream_video_flutter: ^0.5.5
  stream_video_push_notification: ^0.5.5

**Comment by deven98** [comment]
Hi @YashSavsani,

This is an issue with flutter_callkit_incoming which the maintainer is trying to resolve: https://github.com/hiennguyen92/flutter_callkit_incoming/issues/576

They also suggest a temporary workaround here: https://stackoverflow.com/questions/69079963/how-to-set-compilejava-task-11-and-compilekotlin-task-1-8-jvm-target-com/76005200#76005200

Closing this for now - unfortunately, since we do not maintain that plugin, there is not much we can do on our end for this.

Thanks.

**Comment by francisnatty** [comment]
the solution u tagged doesnt work on my end..it doesnt even build @deven98
