### ISSUE TITLE
Call does not end for User A when User B terminates the app

### ISSUE THREAD

**Issue by keshav-sf** [GetStream/stream-video-flutter#807]
There is an issue with the call termination behavior when one participant (User B) closes the app during an ongoing call. 

- When a call is established between **User A** and **User B**, and both users are in the app, everything works as expected.
- However, when **User B** terminates the app, the call ends for **User B**, but **User A** remains in the call. No events are triggered on User A's side, and they remain in the call as though nothing has changed.

**Steps to Reproduce:**
1. Establish a call between **User A** and **User B** (both users are connected and in the app).
2. Let the call continue.
3. **User B** terminates the app.
4. Observe that the call ends for **User B**, but **User A** remains in the call, with no events being triggered.

**Expected Behavior:**
When **User B** terminates the app, **User A** should be notified that the call has ended or **User B** have left the call and should leave the call automatically or trigger the appropriate events on User A’s side.

**Device Information:**

- **Devices Tested:**
  - iPhone 13
  - iPhone 15

- **iOS Versions:**
  - iPhone 13: 18.0.1
  - iPhone 15: 17.6.1

- **Flutter Version:**
  - Flutter 3.24.3 (Stable)

**Comment by Brazol** [comment]
Hi @keshav-sf, thank you for the detailed report. When a user kills the app, the call-disconnection process is not triggered correctly. From the SFU's perspective, this may appear as a connection issue, which is why the user might stay on the call for a bit longer. Eventually, if the user does not reconnect, the SFU will send the `StreamCallParticipantLeftEvent`, and the user will be disconnected.

If the call was initiated as a ringing call and the `dropIfAloneInRingingFlow` flag in `CallPreferences` is set to true, the call may end. Otherwise, the remaining user will continue to stay in the call alone.

We identified a bug on Android devices where the foreground service could remain active, resulting in users staying connected to calls indefinitely. This issue has now been resolved in this [PR](https://github.com/GetStream/stream-video-flutter/pull/812). 

Please let me know if this addresses your concerns and feel free to reopen this issue if it doesn't.
